apiVersion: v1
kind: Service
metadata:
  labels:
    app: golang-template
    role: backend
  name: golang-template-app
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: golang-template
    role: backend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: golang-template
    role: backend
  name: golang-template-app
spec:
  selector:
    matchLabels:
      app: golang-template
      role: backend
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: golang-template
        role: backend
      name: app
    spec:
      containers:
      - env:
        - name: ENVIRONMENT
          value: prod
        - name: LOG_LEVEL
          value: info
        image: gcr.io/searce-anthos-lab/anthos-app
        name: app
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
      serviceAccountName: golang-template-ksa
