apiVersion: v1
kind: Service
metadata:
  labels:
    env: stg
  name: golang-template-app
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    env: stg
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    env: stg
  name: golang-template-app
spec:
  replicas: 1
  selector:
    matchLabels:
      env: stg
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        env: stg
      name: app
    spec:
      containers:
      - env:
        - name: ENVIRONMENT
          value: stg
        - name: LOG_LEVEL
          value: info
        image: gcr.io/searce-anthos-lab/anthos-app:4c61aa2-dirty
        name: app
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
